import type { Metadata } from "next";
import "./style.scss";

export const metadata: Metadata = {
  title: {
    template: "%s - Next Appication",
    default: "Next Appication"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" sizes="48x48" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}